":rocket: feature": ["enhancement/*", "feature/*", "feat/*"]
":blue_book: documentation": ["docs/*", "documentation/*", "doc/*"]
":warning: breaking": ["breaking/*", "break/*"]
":beetle: bug": ["bug/*", "fix/*"]
":lipstick: style": ["style/*", "format/*"]
":package: refactor": ["refactor/*"]
":broom: cleaning": ["remove/*", "clean/*"]
":wrench: build": ["build/*"]
":test_tube: tests": ["test/*", "tests/*", "testing/*"]
":chart_with_upwards_trend: dependency-update": ["update/*", "dep/*", "dependency/*", "dependency-update/*"]
