name: 'Scala Steward Github Action'
author: alejandrohdezma
description: '🤖 A bot that helps you keeping your Scala projects up-to-date '
branding:
  icon:  arrow-up-circle
  color: red

inputs:
  github-repository:
    description: 'Repository to update. The current repository will be used by default'
    default: ''
    required: false
  github-token:
    description: 'Github Personal Access Token with permission to create branches on repo'
    required: true
  sign-commits:
    description: 'Whether to sign commits or not'
    default: 'false'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
