name: Run `npm run all` in the project

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Run checks
        run: npm run all