name: Run `npm run build` and push changes to `master`

on:
  push:
    branches:
      - "master"

jobs:
  build-and-push:
    name: Run `npm run build` and push changes to `master`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          fetch-depth: 0
          ref: master

      - uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458 # v2.5.0
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run build`
        run: npm run build

      - name: Push changes
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Format & build [skip ci]
          branch: master
