name: Release Drafter

on:
  pull_request:
    types: [closed]


jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}