name: Update Major Version Tag

on:
  push:
    tags:
      - "v*"

jobs:
  update-major-version-tag:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@be25c5301723e95e520a4ee375d399d6a30fe6e7 # v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
