name: Update Major Version Tag

on:
  release:
    types: [published]

jobs:
  update-major-version-tag:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@f2014bbbba95b635e990ce512c5653bd0f4753fb # v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
